feat: 동아리 활동 보고서 생성기능 구현
team-dongle/dongle-be-v2 pull request #20
Opened 2024-12-12 08:34 UTC by seokimun

- 동아리 활동 보고서 생성구현
- 이미지 업로드 기능구현

2024-12-12 08:57 UTC, nyongone requested changes
수정 부분이 많습니다.
제일 큰 건 활동 보고서 이미지 업로드 부분인데, 여기는 꼭 다중 파일 업로드에서 단일 파일 업로드로 변경해 주세요.
다른 업로드 컨트롤러 참고해서 response format도 지켜주시고요

2024-12-12 08:57 UTC, nyongone commented on src/controllers/upload.controller.ts
> +  public upladReport: RequestHandler = async (req, res, next) => {
`upladReport` -> `uploadReportImage` 로 네이밍 바꿔주세요.

2024-12-12 08:57 UTC, nyongone commented on src/routes/v1/upload.route.ts
> +  new UploadController().upladReport,
오탈자 제대로 검수 바랍니다.

2024-12-12 08:57 UTC, nyongone commented on src/routes/v1/upload.route.ts
> +  "/report",
`/report` 라고하면 레포트를 업로드하는 것 같으니 `/reportImage`로 라우트 네이밍 바꿔주세요

2024-12-12 08:57 UTC, nyongone commented on src/controllers/upload.controller.ts
> +    const reportImages = req.files as Express.MulterS3.File[];
다중 파일 업로드가 아니라 단일 파일 업로드로 바꿔주세요.
다른 파일 업로드 컨트롤러 참고하면서 작업하시면 될 것 같습니다.

2024-12-12 08:57 UTC, nyongone commented on src/routes/v1/upload.route.ts
> +  upload("reports", env.bucket.allow_exts_img, 5).array("report"),
`reports` -> `reportImages`
단일 파일 업로드로 변경: `.array("report")` -> `.single("images")`

2024-12-12 08:57 UTC, nyongone commented on src/services/report.service.ts
> +    return result;
`return result` -> `return true`

2024-12-12 14:04 UTC, seokimun commented on src/services/report.service.ts
> +    return result;
수정완료하였습니다

2024-12-13 03:15 UTC, nyongone requested changes
수정 바랍니다.

2024-12-13 03:15 UTC, nyongone commented on src/routes/v1/report.route.ts
> +router.post("", authMiddleware, new ReportController().createReport);
...??
`/create`로 다시 수정 바랍니다.

2024-12-13 03:47 UTC, seokimun commented on src/routes/v1/report.route.ts
> +router.post("", authMiddleware, new ReportController().createReport);
수정완료하였습니다

2024-12-13 04:08 UTC, seokimun commented on src/controllers/upload.controller.ts
> +  public upladReport: RequestHandler = async (req, res, next) => {
수정 하였습니다

2024-12-13 04:08 UTC, seokimun commented on src/routes/v1/upload.route.ts
> +  new UploadController().upladReport,
수정하였습니다

2024-12-13 04:08 UTC, seokimun commented on src/routes/v1/upload.route.ts
> +  "/report",
수정하였습니다

2024-12-13 04:08 UTC, seokimun commented on src/controllers/upload.controller.ts
> +    const reportImages = req.files as Express.MulterS3.File[];
수정하였습니다

2024-12-13 04:08 UTC, seokimun commented on src/routes/v1/upload.route.ts
> +  upload("reports", env.bucket.allow_exts_img, 5).array("report"),
수정하였습니다

2024-12-13 04:24 UTC, nyongone requested changes

2024-12-13 04:24 UTC, nyongone commented on src/routes/v1/upload.route.ts
> +  upload("reportImages", env.bucket.allow_exts_img, 5).single("images"),
잘못 알려드렸네요
`images` -> `image`로 변경 부탁드려요
단일 업로드기 때문에 단수형으로 쓰는게 맞는 것 같습니다

2024-12-13 04:29 UTC, seokimun commented on src/routes/v1/upload.route.ts
> +  upload("reportImages", env.bucket.allow_exts_img, 5).single("images"),
수정완료하였습니다

2024-12-13 04:37 UTC, nyongone approved these changes
굿 👍

2024-12-13 04:37 UTC, merged