feat: 동아리 활동 보고서 수정기능 개발
team-dongle/dongle-be-v2 pull request #22
Opened 2024-12-13 07:31 UTC by seokimun

동아리 활동 보고서 수정기능 개발 올립니다.
확인부탁드리겠습니다

2024-12-13 07:53 UTC, nyongone requested changes
확인했습니다.
수정 사항 있으니 확인하고 수정 부탁드립니다.

2024-12-13 07:53 UTC, nyongone commented on src/services/report.service.ts
> +      throw new ApiError("Not Found", StatusCodes.NOT_FOUND);
Not Found 에러 말고 Bad Request 에러 사용해주세요.

2024-12-13 08:09 UTC, seokimun commented on src/services/report.service.ts
> +      throw new ApiError("Not Found", StatusCodes.NOT_FOUND);
수정하였습니다

2024-12-15 04:54 UTC, nyongone requested changes
수정 부탁드립니다.

2024-12-15 04:54 UTC, nyongone commented on src/services/report.service.ts
> +    const result = await Report.findAndCountAll;
이렇게 작성하면 작동 하던가요..?
다른 서비스 파일 보고 적절하게 수정해주세요.

2024-12-15 04:54 UTC, nyongone commented on src/controllers/report.controller.ts
> +      if (req.role !== "CLUB" && req.role !== "ADMIN") {
여기 그냥 `req.role !== "CLUB"` 만 체크해주세요
ADMIN 권한은 체크할 필요 없을 것 같습니다~

2024-12-15 11:02 UTC, nyongone requested changes
수정사항 있습니다.

2024-12-15 15:23 UTC, seokimun commented on src/controllers/report.controller.ts
> +      if (req.role !== "CLUB" && req.role !== "ADMIN") {
수정 완료하였습니다

2024-12-15 15:24 UTC, seokimun commented on src/controllers/report.controller.ts
> +  public updateReport: RequestHandler = async (req, res, next) => {
수정 완료하였습니다

2024-12-15 15:24 UTC, seokimun commented on src/controllers/report.controller.ts
> +  public deleteReport: RequestHandler = async (req, res, next) => {
수정 완료하였습니다

2024-12-16 13:18 UTC, merged